const $=s=>document.querySelector(s);
const scene=$('#landscape'),shelter=$('#shelter'),discover=$('#discover');
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
let target=0,amount=0,velocity=0,center=.5,aim=.5,frame=0;
function draw(){const width=scene.clientWidth;center+=(aim-center)*.065;velocity+=(target-amount)*.018;velocity*=.79;amount+=velocity;if(reduced.matches){amount=target;center=aim;velocity=0}const half=amount*Math.min(width*.24,260);const middle=center*width;const bow=Math.sin(amount*Math.PI)*25;const points=[];for(let i=0;i<=20;i++){let y=i/20;points.push(`${middle-half-Math.sin(y*Math.PI)*bow}px ${y*100}%`)}for(let i=20;i>=0;i--){let y=i/20;points.push(`${middle+half+Math.sin(y*Math.PI)*bow}px ${y*100}%`)}shelter.style.clipPath=`polygon(${points.join(',')})`;if(Math.abs(target-amount)>.0005||Math.abs(velocity)>.0005||Math.abs(center-aim)>.0005)frame=requestAnimationFrame(draw);else {frame=0;if(!target){amount=0;velocity=0;shelter.style.clipPath='polygon(50% 0,50% 0,50% 100%,50% 100%)'}}}
function setShelter(open){target=open?1:0;discover.setAttribute('aria-pressed',String(open));$('#discover-label').textContent=open?'A LITTLE WARMTH. JUST HERE.':'HOLD TO FIND SHELTER';if(!frame)frame=requestAnimationFrame(draw)}
scene.addEventListener('pointerdown',e=>{if(e.button!==0)return;aim=Math.max(.28,Math.min(.72,(e.clientX-scene.getBoundingClientRect().left)/scene.clientWidth));setShelter(true)});
scene.addEventListener('pointermove',e=>{if(target){aim=Math.max(.28,Math.min(.72,(e.clientX-scene.getBoundingClientRect().left)/scene.clientWidth));if(!frame)frame=requestAnimationFrame(draw)}});
window.addEventListener('pointerup',()=>setShelter(false));window.addEventListener('pointercancel',()=>setShelter(false));window.addEventListener('blur',()=>setShelter(false));discover.addEventListener('click',e=>{if(e.detail===0)setShelter(!target)});
const dialog=$('#calendar');const today=new Date();today.setHours(0,0,0,0);let month=new Date(today.getFullYear(),today.getMonth(),1),arrival=null,departure=null,mode='arrival';
const fmt=d=>d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});const key=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function render(){ $('#month-title').textContent=month.toLocaleDateString('en-GB',{month:'long',year:'numeric'});$('#previous').disabled=month<=new Date(today.getFullYear(),today.getMonth(),1);$('#days').replaceChildren();const offset=(month.getDay()+6)%7;for(let i=0;i<offset;i++){const el=document.createElement('span');el.className='empty';$('#days').append(el)}const count=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();for(let day=1;day<=count;day++){const d=new Date(month.getFullYear(),month.getMonth(),day),b=document.createElement('button');b.textContent=day;b.dataset.date=key(d);b.setAttribute('aria-label',d.toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'}));b.disabled=d<today||(mode==='departure'&&arrival&&d<=arrival);const selected=+d===+arrival||+d===+departure;b.setAttribute('aria-pressed',String(selected));if(selected)b.classList.add('selected');if(arrival&&departure&&d>arrival&&d<departure)b.classList.add('in-range');if(+d===+today)b.classList.add('today');b.addEventListener('click',()=>{if(mode==='arrival'){arrival=d;departure=null;mode='departure'}else{departure=d;mode='arrival'}render();const focus=$(`[data-date="${key(d)}"]`);if(!focus.disabled)focus.focus();else $('#days button:not(:disabled)')?.focus()});$('#days').append(b)}$('#arrival strong').textContent=arrival?fmt(arrival):'Choose a date';$('#departure strong').textContent=departure?fmt(departure):'Choose a date';$('#arrival').classList.toggle('active',mode==='arrival');$('#departure').classList.toggle('active',mode==='departure');const nights=arrival&&departure?Math.round((departure-arrival)/86400000):0;$('#hint').textContent=nights?`${nights} ${nights===1?'night':'nights'}. A little time of your own.`:mode==='arrival'?'Choose the day you arrive.':'And the day you leave.';$('#confirm').disabled=!nights;$('#confirm').innerHTML=nights?'KEEP THESE DATES <span>↗</span>':'SELECT YOUR DATES <span>↗</span>';}
$('#book').addEventListener('click',()=>{setShelter(false);render();dialog.showModal()});$('#close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});$('#previous').addEventListener('click',()=>{month.setMonth(month.getMonth()-1);render()});$('#next').addEventListener('click',()=>{month.setMonth(month.getMonth()+1);render()});$('#arrival').addEventListener('click',()=>{mode='arrival';render()});$('#departure').addEventListener('click',()=>{if(arrival)mode='departure';render()});$('#confirm').addEventListener('click',()=>{$('#hint').textContent=`${fmt(arrival)} — ${fmt(departure)}. Your dates are selected; no reservation has been made.`;$('#confirm').textContent='DATES SELECTED ✓';});
